import React, {useEffect, useMemo, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createChart, CandlestickData, IChartApi} from 'lightweight-charts';
import {api, BASE} from './api/client';
import './style.css';

type Bar={time:string;date?:string;open:number;high:number;low:number;close:number;volume:number;ema10?:number;ema20?:number;sma50?:number;sma100?:number;sma200?:number};
type MarkerDraft={marker_type:string; timestamp:string; price:number; timeframe:string; note?:string};
const classes=['A+','Gut','Neutral','Fehlsignal','Bewusst geskippt'];
const structures=['HTF','Pullback','Base','EP'];
const triggers=['Base-BO','U&R','EMA-Reclaim','Reclaim-FT','EP-Trigger'];
const tactics=['ORB m5','ORB m15','ORB m30','PDH Buy-Stop','Sniper','EOTD'];
const levels=['PDH','PDL-Reclaim','ORH m5','ORH m15','ORH m30','Pivot','EMA10','EMA20','Reclaim-Kerzenhoch','Swing-Low'];
const markerTypes=['entry','exit','stop','pivot','trigger_level'];

function toChartTime(b:Bar){return Math.floor(new Date(b.time || `${b.date}T00:00:00Z`).getTime()/1000) as CandlestickData['time']}
function ChartBox({bars, selected}:{bars:Bar[]; selected:number}){
  const ref=useRef<HTMLDivElement>(null); const chartRef=useRef<IChartApi|null>(null);
  useEffect(()=>{ if(!ref.current) return; ref.current.innerHTML=''; const chart=createChart(ref.current,{height:460,layout:{background:{color:'#101722'},textColor:'#d6e2ff'},grid:{vertLines:{color:'#1d2a3a'},horzLines:{color:'#1d2a3a'}}}); chartRef.current=chart; const candle=chart.addCandlestickSeries(); candle.setData(bars.map(b=>({time:toChartTime(b), open:b.open, high:b.high, low:b.low, close:b.close}))); candle.setMarkers(selected>=0&&bars[selected]?[{time:toChartTime(bars[selected]),position:'aboveBar',color:'#f6c343',shape:'arrowDown',text:'selektiert'}]:[]); chart.timeScale().fitContent(); return()=>chart.remove();},[bars,selected]);
  return <div className="chart" ref={ref}/>;
}
function Metric({name,value,warning}:{name:string;value:any;warning?:boolean}){return <tr className={warning?'bad':''}><td>{name}</td><td>{value===null||value===undefined?'—':String(typeof value==='number'?Math.round(value*100)/100:value)}</td></tr>}
function App(){
 const [ticker,setTicker]=useState('NVDA'); const [date,setDate]=useState('2021-11-01'); const [tf,setTf]=useState('daily'); const [cutoff,setCutoff]=useState(''); const [bars,setBars]=useState<Bar[]>([]); const [metrics,setMetrics]=useState<any>({}); const [selected,setSelected]=useState(-1); const [err,setErr]=useState(''); const [msg,setMsg]=useState(''); const [labels,setLabels]=useState<any[]>([]); const [settings,setSettings]=useState<any>({}); const [markerType,setMarkerType]=useState('entry'); const [markerDrafts,setMarkerDrafts]=useState<MarkerDraft[]>([]); const [currentSetup,setCurrentSetup]=useState<number|null>(null);
 const [form,setForm]=useState<any>({label_class:'Gut',structure:'Pullback',trigger:'EMA-Reclaim',tactic:'ORB m30',level_name:'ORH m30',orderly_rating:4,result_is_hypothetical:false});
 const selectedBar=selected>=0?bars[selected]:undefined;
 const setupName=useMemo(()=>`${form.structure} / ${form.trigger} / ${form.tactic} @ ${form.level_name||'Level offen'}`,[form]);
 async function load(){setErr('');setMsg('Lade echte Daten über EODHD/cache ...'); try{const r=await api('/charts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ticker,date,timeframe:tf,cutoff_time:cutoff||undefined})}); setBars(r.bars); setMetrics(r.metrics||{}); setSelected(r.bars.length? r.bars.length-1:-1); setMsg(`${r.bars.length} Kerzen geladen. Playback-Cutoff: ${date}${cutoff?' '+cutoff:''}.`)}catch(e:any){setErr(e.message); setMsg('')}}
 async function check(){setErr(''); try{const r=await api('/availability/m5',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ticker,entry_date:date})}); setMsg(`${r.available?'OK':'Fehlt'}: ${r.message} (${r.bars} Bars)`)}catch(e:any){setErr(e.message)}}
 async function save(){try{const r=await api('/labels',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ticker,setup_name:setupName,...form})}); setCurrentSetup(r.id); for(const m of markerDrafts){await api('/markers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({setup_id:r.id,...m})})} setMsg(`Label gespeichert: ${r.setup_name}; Marker: ${markerDrafts.length}`); setMarkerDrafts([]); refresh()}catch(e:any){setErr(e.message)}}
 async function refresh(){try{setLabels(await api('/labels'))}catch{} try{setSettings(await api('/settings/status'))}catch{}}
 async function upload(file:File){const fd=new FormData(); fd.append('file',file); try{const r=await fetch(`${BASE}/api/imports/csv`,{method:'POST',body:fd}); const j=await r.json(); setMsg(`Importiert: ${j.imported}; Fehler: ${j.errors.length}`); setErr(j.errors.map((x:any)=>`Zeile ${x.row}: ${x.message}`).join('\n')); refresh()}catch(e:any){setErr(e.message)}}
 function addMarker(){if(!selectedBar){setErr('Keine Kerze selektiert.');return} const ts=selectedBar.time||selectedBar.date||date; const price=selectedBar.close; setMarkerDrafts([...markerDrafts,{marker_type:markerType,timestamp:ts,price,timeframe:tf}]); setMsg(`${markerType}-Marker vorgemerkt @ ${price}`)}
 useEffect(()=>{refresh()},[]);
 useEffect(()=>{function onKey(e:KeyboardEvent){if(e.key==='ArrowLeft')setSelected(s=>Math.max(0,s-1)); if(e.key==='ArrowRight')setSelected(s=>Math.min(bars.length-1,s+1)); if(e.code==='Space'){e.preventDefault(); addMarker();}} window.addEventListener('keydown',onKey); return()=>window.removeEventListener('keydown',onKey)},[bars,selected,markerType,markerDrafts,tf]);
 return <main><h1>Setup-Miner · Phase 1 Labeling</h1><p className="warn">Keine künstlichen Intraday-Daten: m15/m30 werden nur aus echten m5-Kerzen aggregiert. Fehlende Werte erhalten Gültigkeitsflags statt Schätzungen.</p>{!settings.api_key_configured&&<p className="error">EODHD API-Key ist nicht konfiguriert. Bitte .env prüfen.</p>}{err&&<pre className="error">{err}</pre>}{msg&&<p className="msg">{msg}</p>}
 <section className="panel"><h2>Daten & Playback</h2><label>Ticker<input value={ticker} onChange={e=>setTicker(e.target.value.toUpperCase())}/></label><label>Playback-Datum<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Cutoff-Zeit ET optional<input placeholder="10:00:00" value={cutoff} onChange={e=>setCutoff(e.target.value)}/></label><label>Timeframe<select value={tf} onChange={e=>setTf(e.target.value)}><option value="daily">Daily</option><option value="5m">m5</option><option value="15m">m15</option><option value="30m">m30</option></select></label><button onClick={check}>m5-Verfügbarkeit prüfen</button><button onClick={load}>Chart laden</button></section>
 <ChartBox bars={bars} selected={selected}/>
 <section className="grid"><div className="panel"><h2>Kennzahlen-Panel</h2><p>Tastatur: Pfeiltasten = Kerze wechseln · Leertaste = Marker setzen.</p><table><tbody><Metric name="Selektierter Preis" value={selectedBar?.close}/><Metric name="ATR(14) $" value={metrics.atr14_dollars}/><Metric name="LoD-Distance %" value={metrics.lod_distance_pct} warning={metrics.lod_rule_valid===false}/><Metric name="LoD-Regel ≤ 70%" value={metrics.lod_rule_valid===null?'nicht berechenbar':metrics.lod_rule_valid}/><Metric name="ATR-Extension SMA50" value={metrics.atr_ext_sma50}/><Metric name="ADR20 %" value={metrics.adr20_pct}/><Metric name="ADR14 %" value={metrics.adr14_pct}/><Metric name="RVOL projiziert" value={metrics.rvol_projected}/><Metric name="Gap %" value={metrics.gap_pct}/><Metric name="PDH" value={metrics.pdh}/><Metric name="PDL" value={metrics.pdl}/><Metric name="Dist EMA10 %" value={metrics.dist_ema10_pct}/><Metric name="Dist EMA20 %" value={metrics.dist_ema20_pct}/><Metric name="Dist SMA50 %" value={metrics.dist_sma50_pct}/><Metric name="Dist SMA200 %" value={metrics.dist_sma200_pct}/></tbody></table></div>
 <div className="panel"><h2>Marker & Label</h2><label>Marker-Typ<select value={markerType} onChange={e=>setMarkerType(e.target.value)}>{markerTypes.map(o=><option key={o}>{o}</option>)}</select></label><button onClick={addMarker}>Marker auf selektierte Kerze</button><ul>{markerDrafts.map((m,i)=><li key={i}>{m.marker_type} · {m.timestamp} · {m.price}</li>)}</ul><p><b>Name:</b> {setupName}</p>{[['label_class',classes],['structure',structures],['trigger',triggers],['tactic',tactics],['level_name',levels]].map(([k,opts]:any)=><label key={k}>{k}<select value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}>{opts.map((o:string)=><option key={o}>{o}</option>)}</select></label>)}<label>Orderly 1-5<input type="number" min="1" max="5" value={form.orderly_rating||''} onChange={e=>setForm({...form,orderly_rating:Number(e.target.value)})}/></label><label>Ergebnis R<input type="number" step="0.1" onChange={e=>setForm({...form,result_r:Number(e.target.value)})}/></label><label><input type="checkbox" checked={form.result_is_hypothetical} onChange={e=>setForm({...form,result_is_hypothetical:e.target.checked})}/> hypothetisch</label><label>MFE R<input type="number" step="0.1" onChange={e=>setForm({...form,mfe_r:Number(e.target.value)})}/></label><label>MAE R<input type="number" step="0.1" onChange={e=>setForm({...form,mae_r:Number(e.target.value)})}/></label><textarea placeholder="Notiz" onChange={e=>setForm({...form,notes:e.target.value})}/><button onClick={save}>Label + Marker speichern</button></div></section>
 <section className="panel"><h2>CSV-Import / Backup / Export</h2><p>Pflichtspalten: ticker, entry_date, label_class, structure, trigger, tactic.</p><input type="file" accept=".csv" onChange={e=>e.target.files&&upload(e.target.files[0])}/><a href={`${BASE}/api/exports/labels.csv`} target="_blank">Labels CSV</a><a href={`${BASE}/api/exports/labels.json`} target="_blank">Labels JSON</a><button onClick={async()=>setMsg(`Backup: ${(await api('/backups',{method:'POST'})).backup}`)}>Backup erstellen</button></section>
 <section className="panel"><h2>Letzte Labels</h2><table><tbody>{labels.map(l=><tr key={l.id}><td>{l.ticker}</td><td>{l.setup_name}</td><td>{l.label_class}</td><td>{l.result_r}</td></tr>)}</tbody></table></section></main>
}
createRoot(document.getElementById('root')!).render(<App/>);
